'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { collection, getDocs, addDoc, doc, deleteDoc, updateDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { UserProfile, UserRole } from '@/lib/types';
import ThemeToggle from '@/components/ThemeToggle';
import BrandIcon from '@/components/BrandIcon';
import styles from '../admin.module.css';

// We manage "Staff Profiles" here. 
// Note: Actual Firebase Auth user creation is separate (usually handled by admin SDK or sign-up flow).
// Here we are creating the authorized user records in Firestore.

export default function StaffPage() {
    const pathname = usePathname();
    const [staff, setStaff] = useState<UserProfile[]>([]);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [loading, setLoading] = useState(true);

    // Form state
    const [formData, setFormData] = useState({
        name: '',
        email: '',
        role: 'staff' as UserRole
    });

    useEffect(() => {
        loadStaff();
    }, []);

    const loadStaff = async () => {
        try {
            const querySnapshot = await getDocs(collection(db, 'users'));
            const loadedStaff = querySnapshot.docs.map(doc => ({
                uid: doc.id,
                ...doc.data()
            } as UserProfile));
            setStaff(loadedStaff);
        } catch (error) {
            console.error("Error loading staff:", error);
        } finally {
            setLoading(false);
        }
    };

    const handleAddStaff = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            // Note: In a real app we would create the Auth user here too, 
            // but for now we just create the Firestore profile which enables role checks.
            // The UID here will be auto-generated by Firestore, which mismatches with Auth UID.
            // In a real flow: Admin creates user -> gets UID -> saves to Firestore.
            // Or Admin invites user -> user signs up -> onCreate trigger saves to Firestore.

            // For Prototype: We'll assume these profiles are used for display/management
            // and act as a whitelist if we implement the "check against users collection" rule.

            const docRef = await addDoc(collection(db, 'users'), {
                ...formData,
                createdAt: new Date().toISOString()
            });

            setStaff([...staff, { ...formData, uid: docRef.id }]);
            setIsModalOpen(false);
            setFormData({ name: '', email: '', role: 'staff' });
            alert('Staff profile added. Note: User must confirm email to link Auth account if implementing Auth triggers.');
        } catch (error) {
            console.error("Error adding staff:", error);
            alert("Failed to add staff member.");
        }
    };

    const handleDelete = async (uid: string) => {
        if (!confirm('Are you sure you want to remove this staff member?')) return;
        try {
            await deleteDoc(doc(db, 'users', uid));
            setStaff(staff.filter(s => s.uid !== uid));
        } catch (error) {
            console.error("Error deleting staff:", error);
        }
    };

    const navItems = [
        { href: '/admin', label: 'Dashboard' },
        { href: '/admin/orders', label: 'Orders' },
        { href: '/admin/tables', label: 'Tables' },
        { href: '/admin/menu', label: 'Menu' },
        { href: '/admin/staff', label: 'Staff' },
        { href: '/admin/analytics', label: 'Analytics' }
    ];

    return (
        <div className={styles.adminLayout}>
            {/* Sidebar */}
            <aside className={styles.sidebar}>
                <div className={styles.logo}>
                    <div className={styles.logoIcon}>
                        <BrandIcon size={24} color="var(--accent-primary)" />
                    </div>
                    <span className={styles.logoText}>Abbottabad Eats</span>
                </div>

                <nav className={styles.navSection}>
                    <div className={styles.navLabel}>Main Menu</div>
                    {navItems.map(item => (
                        <Link
                            key={item.href}
                            href={item.href}
                            className={`${styles.navItem} ${pathname === item.href ? styles.active : ''}`}
                        >
                            <span>{item.label}</span>
                        </Link>
                    ))}
                    <div className={styles.navItem} style={{ marginTop: 'auto', padding: '0 1rem' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', color: 'var(--text-secondary)', fontSize: '0.8rem' }}>
                            <span>Theme</span>
                            <ThemeToggle />
                        </div>
                    </div>
                </nav>
            </aside>

            {/* Main Content */}
            <main className={styles.mainContent}>
                <div className={styles.header}>
                    <div>
                        <h1 className={styles.headerTitle}>Staff Management</h1>
                        <p className={styles.headerSubtitle}>Manage access and roles</p>
                    </div>
                    <button className="btn btn-primary" onClick={() => setIsModalOpen(true)}>
                        + Add Staff
                    </button>
                </div>

                {loading ? (
                    <div>Loading staff...</div>
                ) : (
                    <div className={styles.section}>
                        <table className={styles.table}>
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {staff.map(user => (
                                    <tr key={user.uid}>
                                        <td>{user.name}</td>
                                        <td>{user.email}</td>
                                        <td>
                                            <span className={`badge ${user.role === 'admin' ? 'badge-primary' : 'badge-secondary'}`}>
                                                {user.role}
                                            </span>
                                        </td>
                                        <td>
                                            <button
                                                className="btn btn-sm btn-ghost"
                                                onClick={() => handleDelete(user.uid)}
                                                style={{ color: 'var(--danger)' }}
                                            >
                                                Remove
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </main>

            {/* Add Staff Modal */}
            {isModalOpen && (
                <div className="modal-backdrop" onClick={() => setIsModalOpen(false)}>
                    <div className="modal animate-slideUp" onClick={e => e.stopPropagation()}>
                        <h2 style={{ marginBottom: '1.5rem' }}>Add New Staff Member</h2>
                        <form onSubmit={handleAddStaff}>
                            <div className="form-group" style={{ marginBottom: '1rem' }}>
                                <label style={{ display: 'block', marginBottom: '0.5rem' }}>Name</label>
                                <input
                                    className="input"
                                    type="text"
                                    required
                                    value={formData.name}
                                    onChange={e => setFormData({ ...formData, name: e.target.value })}
                                />
                            </div>
                            <div className="form-group" style={{ marginBottom: '1rem' }}>
                                <label style={{ display: 'block', marginBottom: '0.5rem' }}>Email</label>
                                <input
                                    className="input"
                                    type="email"
                                    required
                                    value={formData.email}
                                    onChange={e => setFormData({ ...formData, email: e.target.value })}
                                />
                            </div>
                            <div className="form-group" style={{ marginBottom: '1.5rem' }}>
                                <label style={{ display: 'block', marginBottom: '0.5rem' }}>Role</label>
                                <select
                                    className="input"
                                    value={formData.role}
                                    onChange={e => setFormData({ ...formData, role: e.target.value as UserRole })}
                                >
                                    <option value="staff">Staff</option>
                                    <option value="kitchen">Kitchen</option>
                                    <option value="admin">Admin</option>
                                </select>
                            </div>
                            <div style={{ display: 'flex', gap: '1rem' }}>
                                <button type="button" className="btn btn-secondary" onClick={() => setIsModalOpen(false)} style={{ flex: 1 }}>
                                    Cancel
                                </button>
                                <button type="submit" className="btn btn-primary" style={{ flex: 1 }}>
                                    Add Member
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}
