'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { QRCodeSVG } from 'qrcode.react';
import { Table } from '@/lib/types';
import { fetchTables, createTable, deleteTable } from '@/lib/storage';
import ThemeToggle from '@/components/ThemeToggle';
import BrandIcon from '@/components/BrandIcon';
import styles from '../admin.module.css';

export default function TablesPage() {
    const pathname = usePathname();
    const [tables, setTables] = useState<Table[]>([]);
    const [selectedTable, setSelectedTable] = useState<Table | null>(null);
    const [showQRModal, setShowQRModal] = useState(false);

    useEffect(() => {
        // initializeData... (Removed)

        const loadTables = async () => {
            const allTables = await fetchTables();
            setTables(allTables.length > 0 ? allTables : []);
        };

        loadTables();
    }, []);

    const getQRUrl = (tableId: string) => {
        // In production, this would be the actual domain
        return `${typeof window !== 'undefined' ? window.location.origin : ''}/customer/${tableId}`;
    };

    const handleDownloadQR = (tableId: string, name: string) => {
        const svg = document.getElementById(`qr-${tableId}`);
        if (svg) {
            const svgData = new XMLSerializer().serializeToString(svg);
            const canvas = document.createElement('canvas');
            const ctx = canvas.getContext('2d');
            const img = new Image();

            // 2048x2048 Ultra-HD for professional printing
            const exportSize = 2048;

            img.onload = () => {
                canvas.width = exportSize;
                canvas.height = exportSize;
                if (ctx) {
                    // White background for visibility
                    ctx.fillStyle = 'white';
                    ctx.fillRect(0, 0, exportSize, exportSize);

                    // Draw QR code scaled to fill
                    ctx.drawImage(img, 0, 0, exportSize, exportSize);

                    // Add table name as label at bottom (optional but professional)
                    ctx.fillStyle = '#1A1A1A';
                    ctx.font = 'bold 80px Inter, sans-serif';
                    ctx.textAlign = 'center';
                    ctx.fillText(`${name}`, exportSize / 2, exportSize - 60);

                    const pngFile = canvas.toDataURL('image/png', 1.0); // 1.0 quality
                    const downloadLink = document.createElement('a');
                    downloadLink.download = `${name.toLowerCase().replace(/\s+/g, '-')}-qr-uhd.png`;
                    downloadLink.href = pngFile;
                    downloadLink.click();
                }
            };

            img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
        }
    };

    const navItems = [
        { href: '/admin', label: 'Dashboard' },
        { href: '/admin/orders', label: 'Orders' },
        { href: '/admin/tables', label: 'Tables' },
        { href: '/admin/menu', label: 'Menu' },
        { href: '/admin/analytics', label: 'Analytics' }
    ];

    const handleAddTable = async () => {
        // ID is now generated by Firestore (UUID)
        // We just assign a friendly name for now, or could ask user for input
        // For simplicity, let's keep the name as "Table X" based on count, but ID is secure.
        const nextNum = tables.length + 1;

        const newTable: Omit<Table, 'id'> = {
            name: `Table ${nextNum}`,
            seats: 4,
            isOccupied: false
        };

        const created = await createTable(newTable);
        if (created) {
            setTables([...tables, created]);
        }
    };

    return (
        <div className={styles.adminLayout}>
            {/* Sidebar */}
            <aside className={styles.sidebar}>
                <div className={styles.logo}>
                    <div className={styles.logoIcon}>
                        <BrandIcon size={24} color="var(--accent-primary)" />
                    </div>
                    <span className={styles.logoText}>Abbottabad Eats</span>
                </div>

                <nav className={styles.navSection}>
                    <div className={styles.navLabel}>Main Menu</div>
                    {navItems.map(item => (
                        <Link
                            key={item.href}
                            href={item.href}
                            className={`${styles.navItem} ${pathname === item.href ? styles.active : ''}`}
                        >
                            <span>{item.label}</span>
                        </Link>
                    ))}
                    <div className={styles.navItem} style={{ marginTop: 'auto', padding: '0 1rem' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', color: 'var(--text-secondary)', fontSize: '0.8rem' }}>
                            <span>Theme</span>
                            <ThemeToggle />
                        </div>
                    </div>
                </nav>
            </aside>

            {/* Main Content */}
            <main className={styles.mainContent}>
                <div className={styles.header}>
                    <div>
                        <h1 className={styles.headerTitle}>Tables</h1>
                        <p className={styles.headerSubtitle}>Manage tables and generate secure QR codes</p>
                    </div>
                    <button
                        className="btn btn-primary"
                        onClick={handleAddTable}
                    >
                        + Add Table
                    </button>
                </div>

                {/* Tables Grid */}
                <div className={styles.tablesGrid}>
                    {tables.map(table => (
                        <div
                            key={table.id}
                            className={`${styles.tableCard} ${table.isOccupied ? styles.occupied : ''}`}
                            style={{ position: 'relative', overflow: 'hidden' }}
                        >
                            {table.isOccupied && <div style={{
                                position: 'absolute',
                                top: 0,
                                left: 0,
                                right: 0,
                                height: '4px',
                                background: 'var(--accent-primary)',
                                boxShadow: '0 0 10px var(--accent-primary)'
                            }} />}

                            <div className={styles.tableCardNumber} style={{ fontSize: '1.5rem', marginBottom: 'var(--space-1)' }}>{table.name}</div>
                            <div className={styles.tableCardSeats} style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: 'var(--space-4)' }}>ID: {table.id.substring(0, 8)}</div>
                            <div className={styles.tableCardSeats} style={{ fontWeight: 600 }}>{table.seats} seats</div>

                            <span className={`${styles.tableCardStatus} ${table.isOccupied ? styles.occupied : styles.available}`} style={{
                                margin: 'var(--space-4) 0',
                                fontWeight: 700,
                                textTransform: 'uppercase',
                                letterSpacing: '0.05em'
                            }}>
                                {table.isOccupied ? 'Occupied' : 'Ready'}
                            </span>

                            <div style={{ display: 'flex', gap: '0.5rem', width: '100%', marginTop: 'auto' }}>
                                <button
                                    className="btn btn-secondary btn-sm"
                                    onClick={() => {
                                        setSelectedTable(table);
                                        setShowQRModal(true);
                                    }}
                                    style={{ flex: 1, height: '40px' }}
                                >
                                    QR Code
                                </button>
                                <button
                                    className="btn btn-sm"
                                    style={{
                                        backgroundColor: 'rgba(255, 59, 48, 0.1)',
                                        color: '#FF3B30',
                                        border: '1px solid rgba(255, 59, 48, 0.2)',
                                        padding: '0 0.8rem',
                                        borderRadius: 'var(--radius-md)',
                                        height: '40px'
                                    }}
                                    onClick={async () => {
                                        if (confirm(`Delete ${table.name}?`)) {
                                            const success = await deleteTable(table.id);
                                            if (success) {
                                                setTables(tables.filter(t => t.id !== table.id));
                                            }
                                        }
                                    }}
                                >
                                    Delete
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            </main>

            {/* QR Modal */}
            {showQRModal && selectedTable && (
                <div className="modal-backdrop" onClick={() => setShowQRModal(false)}>
                    <div className="modal animate-slideUp" onClick={e => e.stopPropagation()}>
                        <h2 style={{
                            textAlign: 'center',
                            marginBottom: 'var(--space-6)',
                            fontSize: 'var(--font-size-xl)'
                        }}>
                            Table {selectedTable.id} QR Code
                        </h2>

                        <div style={{
                            background: 'white',
                            padding: 'var(--space-6)',
                            borderRadius: 'var(--radius-xl)',
                            display: 'flex',
                            justifyContent: 'center',
                            marginBottom: 'var(--space-6)'
                        }}>
                            <QRCodeSVG
                                id={`qr-${selectedTable.id}`}
                                value={getQRUrl(selectedTable.id)}
                                size={250}
                                level="H"
                                includeMargin
                                fgColor="#0a0a0a"
                                bgColor="#ffffff"
                            />
                        </div>

                        <p style={{
                            textAlign: 'center',
                            color: 'var(--text-muted)',
                            fontSize: 'var(--font-size-sm)',
                            marginBottom: 'var(--space-4)'
                        }}>
                            Scan this code to order from Table {selectedTable.id}
                        </p>

                        <div style={{
                            background: 'var(--bg-tertiary)',
                            padding: 'var(--space-3)',
                            borderRadius: 'var(--radius-lg)',
                            textAlign: 'center',
                            marginBottom: 'var(--space-6)',
                            wordBreak: 'break-all',
                            fontSize: 'var(--font-size-sm)',
                            color: 'var(--text-secondary)'
                        }}>
                            {getQRUrl(selectedTable.id)}
                        </div>

                        <div style={{ display: 'flex', gap: 'var(--space-3)' }}>
                            <button
                                className="btn btn-secondary"
                                onClick={() => setShowQRModal(false)}
                                style={{ flex: 1 }}
                            >
                                Close
                            </button>
                            <button
                                className="btn btn-primary"
                                onClick={() => handleDownloadQR(selectedTable.id, selectedTable.name)}
                                style={{ flex: 1 }}
                            >
                                Download Ultra-HD PNG
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
